name: Sample PHP Deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Print global variables
      shell: cmd
      run: env
    - name: Checkout from repo .. ${{ github.event.repository.name }}
      uses: actions/checkout@v3
      with:
       path: deepak_workspace
    - name: copy all files from _work to running server .. 
      shell: cmd
      run: |
          cd D:\actions-runner\_work\training_with_actions\training_with_actions\deepak_workspace
          xcopy . D:\XAMPP\htdocs\git_action_project /y /e
