name: Sample PHP Deployment
  workDirectory: D:\actions-runner\_work\training_with_actions\training_with_actions\deepak_workspace
  productionDirectory: D:\XAMPP\htdocs\git_action_project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout from repo ${{ github.event.repository.name }}
      uses: actions/checkout@v3
      with:
       path: deepak_workspace
    - name: copy all files from _work to running server .. 
      shell: cmd
      run: |
          cd ${{ workDirectory }}
          xcopy . ${{ productionDirectory }} /y /e /h

      
    


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
